#!/bin/bash

echo -e "\033[1;31mDIKKAT!!\033[0m"
echo " "
echo -e "\033[1;31mBU SIFRE SUNUCUYA GIRIS YAPAMAK ICIN KULLANILIR
\033[0m"
echo -e "\033[1;32mYENI SIFRE GIRIN \033[1;32m
DEVAM ETMEK ICIN...\033[1;31m\033[0m"
read  -p : pass
(echo $pass; echo $pass)|passwd 2>/dev/null
sleep 1s
echo -e "\033[1;31mBASARILI BIR SEKILDE DEGISTIRILDI!\033[0m"
sleep 5s
cd
clear

